const countries = {
  Afganistán: 'AF',
  'Åland Islands': 'AX',
  Albania: 'AL',
  Alemania: 'DE',
  Andorra: 'AD',
  Angola: 'AO',
  Anguila: 'AI',
  Antártida: 'AQ',
  'Antigua y Barbuda': 'AG',
  'Antillas Neerlandesas': 'AN',
  'Arabia Saudita': 'SA',
  Argelia: 'DZ',
  Argentina: 'AR',
  Armenia: 'AM',
  Aruba: 'AW',
  Australia: 'AU',
  Austria: 'AT',
  Azerbaiyán: 'AZ',
  Bahamas: 'BS',
  Bahrein: 'BH',
  Bangladesh: 'BD',
  Barbados: 'BB',
  Belarús: 'BY',
  Bélgica: 'BE',
  'Bélgica-Luxemburgo': 'BX',
  Belice: 'BZ',
  Benin: 'BJ',
  Bermudas: 'BM',
  Bhután: 'BT',
  Bolivia: 'BO',
  Bonaire: 'BQ',
  'Bosnia y Herzegovina': 'BA',
  Botswana: 'BW',
  Brasil: 'BR',
  'Brunei Darussalam': 'BN',
  Bulgaria: 'BG',
  'Burkina Faso': 'BF',
  Burundi: 'BI',
  'Cabo Verde': 'CV',
  Camboya: 'KH',
  Camerún: 'CM',
  Canadá: 'CA',
  'Categorías especiales': 'SPE',
  Chad: 'TD',
  Checoslovaquia: 'CS',
  Chile: 'CL',
  China: 'CN',
  Chipre: 'CY',
  Colombia: 'CO',
  'Comando I del Pacífico de Estados Unidos': 'USP',
  Comoras: 'KM',
  'Congo, Rep. del': 'CG',
  'Congo, Rep. Dem. del': 'ZR',
  'Corea, Rep. de': 'KR',
  'Corea, Rep. Dem. de': 'KP',
  'Costa Rica': 'CR',
  Croacia: 'HR',
  Cuba: 'CU',
  Curacao: 'CW',
  Dinamarca: 'DK',
  Djibouti: 'DJ',
  Dominica: 'DM',
  Ecuador: 'EC',
  'Egipto, Rep. Árabe de': 'EG',
  'El Salvador': 'SV',
  'Emiratos Árabes Unidos': 'AE',
  Eritrea: 'ER',
  Eslovenia: 'SI',
  España: 'ES',
  'Estados Unidos': 'US',
  Estonia: 'EE',
  'Etiopía (excluida Eritrea)': 'ET',
  'Etiopía (incluida Eritrea)': 'ET',
  'European Union': 'EU',
  'Ex Sudán': 'SD',
  'Federación de Rusia': 'RU',
  Fiji: 'FJ',
  Filipinas: 'PH',
  Finlandia: 'FI',
  'Fm Panama Cz': 'PCZ',
  'Fm Rhod Nyas': 'ZW1',
  'Fm Tanganyik': 'TAN',
  'Fm Vietnam DR': 'VDR',
  'Fm Vietnam Rp': 'SVR',
  'Fm Zanz-Pemb': 'ZPM',
  Francia: 'FR',
  Gabón: 'GA',
  Gambia: 'GM',
  'Gaza Strip': 'GAZ',
  Georgia: 'GE',
  Ghana: 'GH',
  Gibraltar: 'GI',
  Granada: 'GD',
  Grecia: 'GR',
  Groenlandia: 'GL',
  Guadalupe: 'GP',
  Guam: 'GU',
  Guatemala: 'GT',
  'Guayana Francesa': 'GF',
  Guinea: 'GN',
  'Guinea Ecuatorial': 'GQ',
  'Guinea-Bissau': 'GW',
  Guyana: 'GY',
  Haití: 'HT',
  Honduras: 'HN',
  'Hong Kong (China)': 'HK',
  Hungría: 'HU',
  India: 'IN',
  Indonesia: 'ID',
  'Irán, Rep. Islámica del': 'IR',
  Iraq: 'IQ',
  Irlanda: 'IE',
  'Isla Bouvet': 'BV',
  'Isla Bunker': 'BUN',
  'Isla de Navidad': 'CX',
  'Isla Norfolk': 'NF',
  Islandia: 'IS',
  'Islas Caimán': 'KY',
  'Islas Cocos (Keeling)': 'CC',
  'Islas Cook': 'CK',
  'Islas del Pacífico': 'PCE',
  'Islas Falkland': 'FK',
  'Islas Feroe': 'FO',
  'Islas Georgias del Sur y Sandwich del Sur': 'GS',
  'Islas Heard y McDonald': 'HM',
  'Islas Marshall': 'MH',
  'Islas Salomón': 'SB',
  'Islas Turcas y Caicos': 'TC',
  'Islas Ultramarinas Menores de Estados Unidos': 'UM',
  'Islas Vírgenes (EE.UU.)': 'VI',
  'Islas Vírgenes Británicas': 'VG',
  'Islas Wallis y Futuna': 'WF',
  Israel: 'IL',
  Italia: 'IT',
  Jamaica: 'JM',
  Japón: 'JP',
  'Jhonston Island': 'JT',
  Jordania: 'JO',
  Kazajstán: 'KZ',
  Kenya: 'KE',
  Kirguistán: 'KG',
  Kiribati: 'KI',
  Kosovo: 'XK',
  Kuwait: 'KW',
  Lesotho: 'LS',
  Letonia: 'LV',
  Líbano: 'LB',
  Liberia: 'LR',
  Libia: 'LY',
  Liechtenstein: 'LI',
  Lituania: 'LT',
  Luxemburgo: 'LU',
  Macao: 'MO',
  'Macedonia, ex Rep. Yugoslava de': 'MK',
  Madagascar: 'MG',
  Malasia: 'MY',
  Malawi: 'MW',
  Maldivas: 'MV',
  Malí: 'ML',
  Malta: 'MT',
  Mariana: 'MP',
  Marruecos: 'MA',
  Martinica: 'MQ',
  Mauricio: 'MU',
  Mauritania: 'MR',
  Mayotte: 'YT',
  México: 'MX',
  'Micronesia, Estados Fed. de': 'FM',
  'Midway Islands': 'MI',
  Mónaco: 'MC',
  Mongolia: 'MN',
  Montenegro: 'ME',
  Montserrat: 'MS',
  Mozambique: 'MZ',
  Mundo: 'WLD',
  Myanmar: 'MM',
  Namibia: 'NA',
  Nauru: 'NR',
  Nepal: 'NP',
  Nicaragua: 'NI',
  Níger: 'NE',
  Nigeria: 'NG',
  Niue: 'NU',
  'No especificados': 'UNS',
  Noruega: 'NO',
  'Nueva Caledonia': 'NC',
  'Nueva Zelandia': 'NZ',
  Omán: 'OM',
  'Otra zona de Asia, no esp.': 'OAS',
  'Países Bajos': 'NL',
  Pakistán: 'PK',
  Palau: 'PW',
  Panamá: 'PA',
  'Papua Nueva Guinea': 'PG',
  Paraguay: 'PY',
  'Pen Malaysia': 'PMY',
  Perú: 'PE',
  Pitcairn: 'PN',
  'Polinesia Francesa': 'PF',
  Polonia: 'PL',
  Portugal: 'PT',
  'Puerto Rico': 'PR',
  Qatar: 'QA',
  'Reino Unido': 'GB',
  'República Árabe Siria': 'SY',
  'República Centroafricana': 'CF',
  'República Checa': 'CZ',
  'República de Moldova': 'MD',
  'República Democrática Alemana': 'DDR',
  'República Democrática Popular Lao': 'LAO',
  'República Dominicana': 'DO',
  'República Eslovaca': 'SK',
  Reunión: 'RE',
  Rumania: 'RO',
  Rwanda: 'RW',
  'Ryukyu Is': 'RYU',
  Sabah: 'SBH',
  'Sahara Occidental': 'EH',
  'Saint Kitts y Nevis': 'KN',
  'Saint Kitts-Nevis-Anguilla-Aru': 'KN1',
  Samoa: 'WS',
  'Samoa Americana': 'AS',
  'San Marino': 'SM',
  'San Martín': 'SX',
  'San Pedro y Miquelón': 'PM',
  'San Vicente y las Granadinas': 'VC',
  'Santa Elena': 'SH',
  'Santa Lucía': 'LC',
  'Santa Sede': 'VA',
  'Santo Tomé y Príncipe': 'ST',
  Sarawak: 'SWK',
  Senegal: 'SN',
  'Serbia, Rep. Fed. de (Serbia y Montenegro)': 'RS',
  Seychelles: 'SC',
  'Sierra Leona': 'SL',
  SIKKIM: 'SIK',
  Singapur: 'SG',
  Somalia: 'SO',
  'Sri Lanka': 'LK',
  Sudáfrica: 'ZA',
  Sudán: 'SD',
  'Sudán del Sur': 'SS',
  Suecia: 'SE',
  Suiza: 'CH',
  Suriname: 'SR',
  'Svalbard and Jan Mayen Is': 'SJ',
  Swazilandia: 'SZ',
  Tailandia: 'TH',
  'Taiwán, China': 'TW',
  Tanzanía: 'TZ',
  Tayikistán: 'TJ',
  'Territorio Antártico Británico': 'BAT',
  'Territorio Británico del Océano Índico': 'IO',
  'Territorio Palestino Ocupado': 'PS',
  'Tierras Australes y Antárticas Francesas': 'ATF',
  'Timor Oriental': 'TL',
  Togo: 'TG',
  Tokelau: 'TK',
  Tonga: 'TO',
  'Trinidad y Tobago': 'TT',
  Túnez: 'TN',
  Turkmenistán: 'TM',
  Turquía: 'TR',
  Tuvalu: 'TV',
  Ucrania: 'UA',
  Uganda: 'UG',
  'Unión Soviética': 'SU',
  Uruguay: 'UY',
  Uzbekistán: 'UZ',
  Vanuatu: 'VU',
  Venezuela: 'VE',
  'Viet Nam': 'VN',
  'Wake Island': 'WK',
  'Yemen, Rep. del': 'YE',
  'Yemen, Rep. Dem. Del': 'YD',
  'Yugoslavia, Rep. Fed. de (Serbia y Montenegro)': 'YU',
  Zambia: 'ZM',
  Zimbabwe: 'ZW'
}

export { countries }
